version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    binary: kubectl-dup
    ldflags:
      - -s -w

checksum:
  name_template: "{{ .ProjectName }}_{{ .Tag }}_checksums.txt"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  use: github

snapshot:
  version_template: "{{ incminor .Tag }}-dev-{{ .ShortCommit }}"
